### ISSUE TITLE
flatpickr@4.6.2 upgrade

### ISSUE THREAD

**Issue by jvi-mastercore** [jacobmischka/svelte-flatpickr#13]
Is this gonna be upgraded to flatpickr@4.6.2? I need some new features that comes with this version.

Thanks for the time that you put into this you've really made our lives easier :).

**Comment by jacobmischka** [comment]
This shouldn't be necessary, as `flatpickr` is a non-bundled dependency. Running `npm upgrade` (or yarn) in your own project should update flatpickr.
