### ISSUE TITLE
Can't get to work with custom element

### ISSUE THREAD

**Issue by aunumever** [jacobmischka/svelte-flatpickr#20]
I can't seem to get this package to work properly with any custom elements.

Even with a barebones implementation I get: 

```
TypeError: Cannot read property 'nodeName' of null
Uncaught (in promise) TypeError: fp.setDate is not a function
```

Here is the implementation:

```
<script>
  import Flatpickr from 'svelte-flatpickr'
  import 'flatpickr/dist/flatpickr.css'
  import 'flatpickr/dist/themes/light.css'

  const flatpickrOptions = {
    enableTime: true,
    wrap: true,
    element: '#test',
    onChange: (selectedDates, dateStr, instance) => {
      console.log('Options onChange handler', selectedDates, dateStr)
    }
  }
  
  let date
</script>

<Flatpickr options={ flatpickrOptions } bind:value={ date } element='#test'>
  <input id='test' type='text' />
</Flatpickr>
```

Also, FYI, the example code in the repo does not work. It throws the following error:

```
Directive value must be a JavaScript expression enclosed in curly braces
29:     bind:value={date}
30:     placeholder="optional placeholder"
31:     on:change="handleChange(...event)" />
                   ^
32: </div>
```

Wrapping the expression in curly braces produces:

```
'event' is not defined
29:     bind:value={date}
30:     placeholder="optional placeholder"
31:     on:change="{ handleChange(...event) }" />
                                     ^
32: </div>
```

**Comment by buzato** [comment]
Hi @navimaia 

I use custom element that way:
```js
<Flatpickr options="{ flatpickrOptions }" bind:value={newCompromise.startDate} on:change={handleChange} element="#my-picker">
   <div class="flatpickr" id="my-picker">
        <input type="text" class="my-custom-class" placeholder="Select Date.." data-input>
    </div>
</Flatpickr>
```
Perhaps the important thing is the `<div>` with the `id="my-custom-id"` and the `<input>` with `date-input` prop

and for on:change try this
   ` on:change={handleChange} `
```js
const handleChange = ({ detail }) => {
    const [selectedDates, dateStr, instance] = detail
    console.log('Svelte onChange handler', selectedDates, dateStr, instance)
  }
```

I hope I helped!
But I think you've already solved this problem

ps: i'm brazilian, sorry for my bad english 😅

**Comment by jacobmischka** [comment]
Ah yeah, sorry about the example not working anymore, it hasn't been updated since Svelte 2.

**Comment by cicerchia** [comment]
@jacobmischka can you please update the example the correct way? I don't know how to write it right.

I'm getting `fp.setDate is not a function` too.

**Comment by jacobmischka** [comment]
The example has been updated, it should work now.

Working Code Sandbox: https://codesandbox.io/s/serene-northcutt-fgxdh?file=/App.svelte
