### ISSUE TITLE
We need a CHANGELOG

### ISSUE THREAD

**Issue by frederikhors** [jacobmischka/svelte-flatpickr#24]
Can you write a CHANGELOG?

What changed from 2.4.0 to 3.0.0?

Thanks.

**Comment by jacobmischka** [comment]
Not much, I fixed a bug related to props being propagated to the underlying input element. I also updated the example in the README and added a test directory with a running example. Of course, feel free to browse the commits to see the changes for yourself.

A changelog would be nice, but I don't really plan on maintaining one, sorry. Pull requests welcome!
