### ISSUE TITLE
open on:click

### ISSUE THREAD

**Issue by blazzjosh** [jacobmischka/svelte-flatpickr#25]
Cooool Component!

How would i trigger the .open() function on:click on the calendar svg
REPL:
https://svelte.dev/repl/fc310fe6642e47faa4deb2f4dd43bf51?version=3.27.0

Thanks Mate!

**Comment by chovy** [comment]
wrap in anchor.

**Comment by blazzjosh** [comment]
@chovy i understand not anchor - can you please show how in REPL?

**Comment by jacobmischka** [comment]
You can do this now in `3.1.0` by binding to the `fp` or `flatpickr` properties: https://svelte.dev/repl/8b2c3e652cb2435b8b671ce9686dad44?version=3.27.0

However, it seems a bug in flatpickr itself (not this wrapper) is causing the `open()` calls to immediately be closed, for some reason. Not sure why that is, but it's not the fault of this package.

**Comment by blazzjosh** [comment]
binding to ```flatpickr``` gives the desired behaviour; I modified like so:

https://svelte.dev/repl/bd9890966e6b4a9aa4ccd4ddc381cbd2?version=3.27.0

**Comment by jacobmischka** [comment]
Hm, yeah, it seems the `fp` binding doesn't want to work? Not sure what's going on, I don't think I'm doing anything wrong, I think I can export the same variable twice under two different names?
