### ISSUE TITLE
Wrong typescript types, `id` is not recognized

### ISSUE THREAD

**Issue by frederikhors** [jacobmischka/svelte-flatpickr#31]
I think we should generate types with https://github.com/sveltejs/language-tools/tree/master/packages/svelte2tsx because I have this error using `id` prop.

Screen:

![image](https://user-images.githubusercontent.com/41120635/133495392-ad30b4ac-e222-4c1e-9db4-a89867b9eede.png)

**Comment by jacobmischka** [comment]
I would love to, but I honestly have no idea how that package is supposed to work. What am I supposed to do with it, do you know? The single bare example in the README makes no sense to me.

**Comment by frederikhors** [comment]
Ok. So for the first question I think we should use SvelteKit here and it's amazing `package` feature: https://kit.svelte.dev/docs#command-line-interface-svelte-kit-package.

For the second: I need that indeed. I need to pass `id` all under on the `input` element.

**Comment by jacobmischka** [comment]
I don't plan on refactoring to use SvelteKit at this time. I believe 3.2.1 typings should support HTMLInputElement prop types now, let me know if not.

**Comment by frederikhors** [comment]
Ok. I'll try in a few days. For SvelteKit, are you willing to accept a PR by me?

**Comment by jacobmischka** [comment]
Probably not without a better reason to, which I don't foresee. I honestly doubt it handles the input props correctly anyway, I'd rather just fine tune the typings manually for now.

**Comment by frederikhors** [comment]
It works now. You amazing.

![image](https://user-images.githubusercontent.com/41120635/133894479-087863d9-fa7c-4666-88d7-212e9ceca8b5.png)
