### ISSUE TITLE
Type 'Date' is missing the following properties from type 'string[]': length, pop, push, concat, and 29 more. ts(2322)

### ISSUE THREAD

**Issue by frederikhors** [jacobmischka/svelte-flatpickr#32]
I'm using the below code and I'm having this Typescript error, **why**?

```svelte
<script lang="ts">
	import Flatpickr from "svelte-flatpickr";

	export let selectedDateTime: Date = null;
  // ...
</script>

<Flatpickr
	{id}
	bind:value={selectedDateTime}
/>
```

![image](https://user-images.githubusercontent.com/41120635/133920210-cdc58287-ead2-4ddb-923c-566a3dd4b83b.png)

**Comment by jacobmischka** [comment]
Are you on 3.2.2? That was an issue in 3.2.1 but I thought I fixed it.

**Comment by frederikhors** [comment]
`"svelte-flatpickr": "3.2.2",`

**Comment by jacobmischka** [comment]
Okay, try 3.2.3.

**Comment by frederikhors** [comment]
It works now.
