### ISSUE TITLE
When using svelte-flatpickr with mode: 'range', the value can be of type Date [] but its missing in types

### ISSUE THREAD

**Issue by gregroyal** [jacobmischka/svelte-flatpickr#33]
When using svelte-flatpickr with mode: 'range', the value can be of type Date [] but its missing in types.

The only acceptable types for the value is string | Date, but when using range it should also be Date []

**Comment by gregroyal** [comment]
https://github.com/jacobmischka/svelte-flatpickr/pull/34

**Comment by jacobmischka** [comment]
Thanks! Published in `3.2.4`.
