### ISSUE TITLE
fp.setDate is not a function

### ISSUE THREAD

**Issue by cicerchia** [jacobmischka/svelte-flatpickr#36]
I'm using this code:

```svelte
<script lang="ts">
	import Flatpickr from "svelte-flatpickr";
</script>

<Flatpickr bind:value={selectedDateTime} element="#my-picker">
	<div class="flatpickr" id="my-picker">
		<input
			type="text"
			class="my-custom-class"
			placeholder="Select Date..."
			data-input
		/>

		<a class="input-button" title="clear" data-clear>
			<i class="icon-close"></i>
		</a>
	</div>
</Flatpickr>
```

But I get this error:

```
Uncaught (in promise) TypeError: fp.setDate is not a function
    at Object.$$self.$$.update (Flatpickr.svelte? [sm]:28)
    at update (index.mjs:1053)
    at flush (index.mjs:1025)
    at update2 (index.mjs:1377)
    at index.mjs:1384
```

**Comment by jacobmischka** [comment]
Your example works fine (except that you're using an `<a>` tag for what should really be a `<button>`): https://codesandbox.io/s/serene-northcutt-fgxdh?file=/App.svelte

Seems like something else in your configuration is going wrong. Please make sure you're using updated versions of all dependencies.

**Comment by cicerchia** [comment]
I understand that the problem comes when I use that component twice in another component.

**Comment by cicerchia** [comment]
Copy & paste in your example and you'll see the error.

**Comment by cicerchia** [comment]
![image](https://user-images.githubusercontent.com/70173987/140967581-dbd44767-3cc7-47d2-a3fe-43e5f743bea9.png)

I'm sorry I don't have codesandbox account.

**Comment by jacobmischka** [comment]
On the web IDs must be unique to the page, you cannot use the same `id` for more than one element on the same page.

Change your IDs to make them unique.

```svelte
	<Flatpickr bind:value={selectedDateTime} element="#my-picker">
    <div class="flatpickr" id="my-picker">
      <input
        type="text"
        class="my-custom-class"
        placeholder="Select Date..."
        data-input
      />

      <button type="button" data-clear>Clear</button>
    </div>
  </Flatpickr>

  <Flatpickr bind:value={selectedDateTime} element="#my-picker2">
    <div class="flatpickr" id="my-picker2">
      <input
        type="text"
        class="my-custom-class"
        placeholder="Select Date..."
        data-input
      />

      <button type="button" data-clear>Clear</button>
    </div>
  </Flatpickr>
```

**Comment by jacobmischka** [comment]
If you need to do this programmatically in a component, you can use something like [`gud`](https://www.npmjs.com/package/gud) to generate a unique ID at runtime.
