### ISSUE TITLE
Small error message when using 'mode: range' in options.

### ISSUE THREAD

**Issue by delay** [jacobmischka/svelte-flatpickr#40]
When adding mode: 'range' into my options for flatpickr I get this error message.  It still works as expected, but it just throws this error message.  Thanks for any input...

`Type '{ mode: string; dateFormat: string; defaultDate: string; enableTime: boolean; onChange: (selectedDates: any, dateStr: any) => void; }' is not assignable to type 'Partial<BaseOptions>'.`

`	const options = {
		mode: 'range',
		dateFormat: 'm/d/Y',
		defaultDate: '',
		enableTime: false,
		onChange: function (selectedDates, dateStr) {
			onDone(selectedDates[0], selectedDates[1], dateStr);
		}`

**Comment by jacobmischka** [comment]
Interesting, it seems TypeScript isn't inferring that `mode` is a constant.

This might work:

```ts
mode: 'range' as const,
```

**Comment by delay** [comment]
Thanks so much for your help!  That solved the issue.
