### ISSUE TITLE
If I use `altInput: true` I can change the value but it's not changed the value

### ISSUE THREAD

**Issue by frederikhors** [jacobmischka/svelte-flatpickr#46]
If I use `altInput: true` I can change the value but it's not changed the value.

**Comment by frederikhors** [comment]
Sorry. It's the same also without `altInput`.

If I write manually the date I need to confirm it with keyboard Enter button.

If I simply click outside it doesn't change the value.

**Comment by jacobmischka** [comment]
With `allowInput`, you mean? I think that's the same behavior with vanilla flatpickr:

https://user-images.githubusercontent.com/3939997/175936072-dce8acfa-8bc0-4f9a-aa8e-be8b1ec798d6.mp4

https://codesandbox.io/s/clever-montalcini-shp5l8?file=/App.svelte

Let me know if I'm misunderstanding something.

**Comment by frederikhors** [comment]
Yeah. It's not your fault. Sorry.
