### ISSUE TITLE
How do I use wrap: true? 

### ISSUE THREAD

**Issue by asuraphel** [jacobmischka/svelte-flatpickr#48]
Thanks for creating this library. I want Flatpickr to wrap a cancel icon inside the input. How do I do it? Thanks!

**Comment by jacobmischka** [comment]
Did you see the example in the README? https://github.com/jacobmischka/svelte-flatpickr#external-elements

**Comment by asuraphel** [comment]
Thanks @jacobmischka. Should have read till the end!
